/**
 * MarkdownExporter - Generates benchmark reports in Markdown format
 */

import type { BenchmarkResults } from '../benchmarking/types';

/**
 * Format percentage
 */
function formatPercent(value: number): string {
  return `${(value * 100).toFixed(1)}%`;
}

/**
 * Format confidence interval
 */
function formatCI(ci?: [number, number]): string {
  if (!ci) return '---';
  return `[${(ci[0] * 100).toFixed(1)}%, ${(ci[1] * 100).toFixed(1)}%]`;
}

/**
 * Format time duration
 */
function formatTime(ms: number): string {
  if (ms < 1000) return `${Math.round(ms)}ms`;
  const seconds = ms / 1000;
  if (seconds < 60) return `${seconds.toFixed(1)}s`;
  const minutes = Math.floor(seconds / 60);
  const secs = Math.round(seconds % 60);
  return `${minutes}m ${secs}s`;
}

/**
 * Export benchmark results to Markdown format
 */
export function exportMarkdown(results: BenchmarkResults): string {
  const lines: string[] = [];
  const { config, matrix, rankings, summary, metadata, matchups } = results;

  // Header
  lines.push('# ManaCore Benchmark Report');
  lines.push('');
  lines.push(`**Generated:** ${metadata.endTime}`);
  if (metadata.preset) {
    lines.push(`**Preset:** ${metadata.preset}`);
  }
  lines.push(`**Seed:** ${metadata.seed}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Bots compared:** ${summary.botsCompared}`);
  lines.push(`- **Total matchups:** ${summary.totalMatchups}`);
  lines.push(`- **Total games:** ${summary.totalGames}`);
  lines.push(`- **Games per matchup:** ${config.gamesPerMatchup}`);
  lines.push(`- **Duration:** ${formatTime(summary.totalDurationMs)}`);
  lines.push(`- **Throughput:** ${summary.gamesPerSecond.toFixed(1)} games/sec`);
  lines.push('');

  // Rankings Table
  lines.push('## Bot Rankings');
  lines.push('');
  lines.push('Ranked by average win rate across all matchups.');
  lines.push('');

  const hasElo = rankings.some((r) => r.elo !== undefined);
  const hasCI = rankings.some((r) => r.confidenceInterval !== undefined);

  // Build header row
  let headerRow = '| Rank | Bot | Avg Win% |';
  let alignRow = '|:----:|:----|:--------:|';

  if (hasCI) {
    headerRow += ' 95% CI |';
    alignRow += ':-------:|';
  }
  if (hasElo) {
    headerRow += ' Elo |';
    alignRow += ':---:|';
  }
  headerRow += ' Games | W/L/D |';
  alignRow += ':-----:|:-----:|';

  lines.push(headerRow);
  lines.push(alignRow);

  rankings.forEach((ranking, index) => {
    let row = `| ${index + 1} | ${ranking.bot} | ${formatPercent(ranking.avgWinRate)} |`;
    if (hasCI) {
      row += ` ${formatCI(ranking.confidenceInterval)} |`;
    }
    if (hasElo) {
      row += ` ${ranking.elo ?? '---'} |`;
    }
    row += ` ${ranking.gamesPlayed} | ${ranking.wins}/${ranking.losses}/${ranking.draws} |`;
    lines.push(row);
  });

  lines.push('');

  // Win Rate Matrix
  lines.push('## Win Rate Matrix');
  lines.push('');
  lines.push(
    "Each cell shows the row bot's win rate when playing as Player 1 against the column bot.",
  );
  lines.push('');

  const bots = config.bots;

  // Header row
  let matrixHeader = '| |';
  let matrixAlign = '|:----|';
  for (const bot of bots) {
    matrixHeader += ` ${bot} |`;
    matrixAlign += ':------:|';
  }
  lines.push(matrixHeader);
  lines.push(matrixAlign);

  // Data rows
  for (const bot1 of bots) {
    let row = `| **${bot1}** |`;
    for (const bot2 of bots) {
      const winRate = matrix[bot1]?.[bot2] ?? 0;
      row += ` ${formatPercent(winRate)} |`;
    }
    lines.push(row);
  }

  lines.push('');

  // Detailed Matchup Results (if CIs are available)
  if (hasCI) {
    lines.push('## Detailed Matchup Results');
    lines.push('');
    lines.push('| P1 | P2 | P1 Win% | 95% CI | Games |');
    lines.push('|:---|:---|:-------:|:------:|:-----:|');

    for (const m of matchups) {
      if (m.bot1 !== m.bot2) {
        // Skip mirrors for detailed view
        lines.push(
          `| ${m.bot1} | ${m.bot2} | ${formatPercent(m.winRate)} | ${formatCI(m.confidenceInterval)} | ${m.totalGames} |`,
        );
      }
    }

    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by ManaCore Benchmark Suite v' + metadata.version + '*');
  lines.push('');

  return lines.join('\n');
}
